DoWhat.WebMVC/Controllers/CatagoryController.cs
using DoWhat.Contracts;
using DoWhat.Models.CatagoryModels;
using DoWhat.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoWhat.WebMVC.Controllers
{
    [Authorize]
    public class CatagoryController : Controller
    {
        //private readonly ICatagoryService _catagoryService;
        //public CatagoryController(ICatagoryService catagoryService)
        //{
        //    _catagoryService = catagoryService;
        //}


        // GET: Catagory/index
        public ActionResult Index()
        {
            var service = CreateCatagoryService();
            var model = service.GetCatagories();
            return View(model.OrderBy(cat => cat.Name));
            //var model = _catagoryService.GetCatagories();
            //return View(model.OrderBy(cat => cat.Name));
        }

        // GET: Catagory/Create
        public ActionResult Create()
        {
            return View();
        }

        // Catagory/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CatagoryCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateCatagoryService();

            if (service.CreateCatagory(model))
            {
                TempData["SaveResult"] = " You added a Catagory.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Catagory could not be added.");
            return View(model);
        }

        // Catagory/Details/{id}
        public ActionResult Details(int id)
        {
            var svc = CreateCatagoryService();
            var model = svc.GetCatagoryById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateCatagoryService();
            var detail = service.GetCatagoryById(id);
            var model =
                new CatagoryEdit
                {
                    CatagoryId = detail.CatagoryId,
                    Name = detail.Name,
                    Description = detail.Description
                };
            return View(model);
        }

        [HttpPost] // Catagory/Edit/{id}
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CatagoryEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.CatagoryId != id)
            {
                ModelState.AddModelError("", "Catagory ID Missmatch");
                return View(model);
            }

            var service = CreateCatagoryService();

            if (service.UpdateCatagory(model))
            {
                TempData["SaveResult"] = " Catagory was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Catagory could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateCatagoryService();
            var model = svc.GetCatagoryById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCatagory(int id)
        {
            var service = CreateCatagoryService();
            service.DeleteCatagory(id);
            TempData["SaveResult"] = " Catagory was DELETED.";
            return RedirectToAction("Index");
        }


        // Helper Method
        private CatagoryService CreateCatagoryService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId()); // this needs to be in each model that calls for it?
            var service = new CatagoryService(userId);
            return service;
        }
    }
}

DoWhat.WebMVC/Controllers/ResourceController.cs
using DoWhat.Contracts;
using DoWhat.Data;
using DoWhat.Models.ResourceModels;
using DoWhat.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoWhat.WebMVC.Controllers
{
    [Authorize]
    public class ResourceController : Controller
    {

        public ActionResult Index()
        {
            var service = CreateResourceService();
            var model = service.GetResources();
            return View(model.OrderBy(heading => heading.Thing.Heading));
        }

        // *** GET: Reource/Thing/{id}
        [ActionName("IndexByThing")]
        public ActionResult IndexByThing(int id)
        {
            var service = CreateResourceService();
            var model = service.GetResourceListByThing(id);
            return View(model.OrderBy(created => created.CreatedUtc));
        }

        // GET: Resource/Create
        public ActionResult Create()
        {
            var service = CreateResourceService();
            ViewBag.Things = service.ThingsToList();
            return View();
        }

        // Resource/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ResourceCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateResourceService();

            if (service.CreateResource(model))
            {
                TempData["SaveResult"] = " You added a Resource.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Resource could not be added.");
            return View(model);
        }

        // Resource/Details/{id}
        public ActionResult Details(int id)
        {
            var svc = CreateResourceService();
            var model = svc.GetResourceById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateResourceService();
            var detail = service.GetResourceById(id);
            ViewBag.Things = service.ThingsToList();
            var model =
                new ResourceEdit
                {
                    ResourceId = detail.ResourceId,
                    Title = detail.Title,
                    Content = detail.Content,
                    ThingId = detail.ThingId
                };
            return View(model);
        }

        [HttpPost] // Resource/Edit/{id}
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ResourceEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.ResourceId != id)
            {
                ModelState.AddModelError("", "Resource ID Missmatch");
                return View(model);
            }
            var service = CreateResourceService();
            if (service.UpdateResource(model))
            {
                TempData["SaveResult"] = " Resource was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Resource could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateResourceService();
            var model = svc.GetResourceById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteResource(int id)
        {
            var service = CreateResourceService();
            service.DeleteResource(id);
            TempData["SaveResult"] = " Resource was DELETED.";
            return RedirectToAction("Index");
        }

        // helper method
        private ResourceService CreateResourceService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ResourceService(userId);
            return service;
        }
    }
}

DoWhat.WebMVC/Controllers/ThingController.cs
using DoWhat.Contracts;
using DoWhat.Data;
using DoWhat.Models.ThingModels;
using DoWhat.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoWhat.WebMVC.Controllers
{
    [Authorize]
    public class ThingController : Controller
    {
        // GET: Thing/index
        public ActionResult Index()
        {
            var service = CreateThingService();
            var model = service.GetThings();
            return View(model.OrderBy(time => time.TimeAlloted));
        }

        public ActionResult IndexCompleted()
        {
            var service = CreateThingService();
            var model = service.GetAllCompletedThings();
            return View(model.OrderBy(time => time.TimeAlloted));
        }

        // GET: Thing/IndexByCatagory/{id}
        public ActionResult IndexByCatagory(int id)
        {
            var service = CreateThingService();
            var model = service.GetThingListByCatagory(id);
            return View(model.OrderBy(time => time.TimeAlloted));
        }

        // GET: Thing/SelectThing
        public ActionResult SelectThing()
        {
            var service = CreateThingService();
            ViewBag.Catagories = service.CatagoriesToList();
            return View(new ThingSelection());
        }

        // GET: Thing/SelectThing
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SelectThing(ThingSelection model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateThingService();
            ViewBag.Catagories = service.CatagoriesToList();
            model.ThingsSelected = service.GetSelectedThing(model);
            return View(model);
        }

        // GET: Thing/Create
        public ActionResult Create()
        {
            var service = CreateThingService();
            //*var catagorySelectList = service.CatagoriesToList();
            //*ViewBag.Catagories = catagorySelectList;
            ViewBag.Catagories = service.CatagoriesToList();
            // shorter version version ^^

            return View();
        }

        // Thing/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ThingCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateThingService();
            if (service.CreateThing(model))
            {
                TempData["SaveResult"] = " You added a Thing.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Thing could not be added.");
            return View(model);
        }

        // Thing/Details/{id}
        public ActionResult Details(int id)
        {
            var svc = CreateThingService(); 
            var model = svc.GetThingById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateThingService();
            var detail = service.GetThingById(id);
            ViewBag.Catagories = service.CatagoriesToList();
            var model =
                new ThingEdit
                {
                    ThingId = detail.ThingId,
                    Heading = detail.Heading,
                    CatagoryId = detail.CatagoryId,
                    TimeAllotted = detail.TimeAllotted
                };
            return View(model);
        }

        [HttpPost] // Thing/Edit/{id}
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ThingEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.ThingId != id)
            {
                ModelState.AddModelError("", "Thing ID Missmatch");
                return View(model);
            }
            var service = CreateThingService();
            if (service.UpdateThing(model))
            {
                TempData["SaveResult"] = " Thing was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thing could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateThingService();   
            var model = svc.GetThingById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteThing(int id)
        {
            var service = CreateThingService();
            service.DeleteThing(id);
            TempData["SaveResult"] = " Thing was DELETED.";
            return RedirectToAction("Index");
        }

        // helper method
        private ThingService CreateThingService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ThingService(userId);
            return service;
        }
    }
}

DoWhat.WebMVC/Views/Thing/Create.cshtml
@model DoWhat.Models.ThingModels.ThingCreate

@{
    ViewBag.Title = "Create";
}

<h2>Make a Thing</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Make a Thing</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Heading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeAllotted, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("TimeAllotted", new List<SelectListItem> 
                {
                    new SelectListItem{ Text="5 min", Value = "5"},
                    new SelectListItem{ Text="15 min", Value = "15"},
                    new SelectListItem{ Text="30 min", Value = "30"},
                    new SelectListItem{ Text="45 min", Value = "45"},
                    new SelectListItem{ Text="1 hour", Value = "60"},
                    new SelectListItem{ Text="1 and a 1/2 hours", Value = "90"},
                    new SelectListItem{ Text="2 hours", Value = "120"},
                    new SelectListItem{ Text="3 hours", Value = "180"},
                })
            </div>
        </div>

        <div class="form-group"> 
            @Html.LabelFor(model => model.CatagoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CatagoryId, new SelectList(ViewBag.Catagories, "CatagoryId", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CatagoryId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoWhat.WebMVC/Views/Thing/Delete.cshtml
@model DoWhat.Models.ThingModels.ThingDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Thing</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>ThingDetail</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ThingId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThingId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Heading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Heading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoWhat.WebMVC/Views/Thing/Details.cshtml
@model DoWhat.Models.ThingModels.ThingDetail

@{
    ViewBag.Title = "Details";
}

<h2>Thing Detail</h2>

<div>
    @*<h4>Thing Detail</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.HiddenFor(model => model.ThingId)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Heading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Heading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Catagory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catagory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>
</div>


<p>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.ThingId }) |
    @Html.ActionLink("Add Resource", "Create", "Resource")
</p>
<p>
    @Html.ActionLink("DELETE", "Delete", new { id = Model.ThingId })
</p>

DoWhat.WebMVC/Views/Thing/Index.cshtml
@model IEnumerable<DoWhat.Models.ThingModels.ThingListItem>

@{
    ViewBag.Title = "Index";
}

<h2>List of Things</h2>
<p>(sorted by Time Allotted)</p>

<p>
    @Html.ActionLink("Make a Thing", "Create", "Thing", null, new { @class = "btn btn-primary btn-large" })
</p>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
        @TempData["SaveResult"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Catagory.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Heading)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeAlloted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeAlloted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ThingId }) |
                @Html.ActionLink("Details", "Details", new { id=item.ThingId }) |
                @Html.ActionLink("Resources", "IndexByThing", "Resource", new { id = item.ThingId }, null)
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("< Back to Main Page", "Index", "Home") |
    @Html.ActionLink("Show Completed Things", "IndexCompleted")
</div>

DoWhat.WebMVC/Views/Thing/IndexByCatagory.cshtml
@model IEnumerable<DoWhat.Models.ThingModels.ThingListByCatagory>

@{
    ViewBag.Title = "IndexByCatagory";
}

<h2>Things in Catagory</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.Heading)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeAlloted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeAlloted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ThingId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ThingId })
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("< Back to List of Catagories", "Index", "Catagory")
</p>

DoWhat.WebMVC/Views/Thing/IndexCompleted.cshtml
@model IEnumerable<DoWhat.Models.ThingModels.ThingListItem>

@{
    ViewBag.Title = "IndexCompleted";
}

<h2>List of Completed Things</h2>
<p>(sorted by Time Allotted)</p>

<p>
    @Html.ActionLink("Make a Thing", "Create", "Thing", null, new { @class = "btn btn-primary btn-large" })
</p>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
        @TempData["SaveResult"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Catagory.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Heading)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeAlloted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeAlloted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ThingId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ThingId }) |
                @Html.ActionLink("Resources", "IndexByThing", "Resource", new { id = item.ThingId }, null)
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("< Back to Main Page", "Index", "Home") |
    @Html.ActionLink("Show Things to do", "Index")
</div>

DoWhat.WebMVC/Views/Thing/SelectThing.cshtml
@model DoWhat.Models.ThingModels.ThingSelection

@{
    ViewBag.Title = "SelectThing";
}

<h2>Find a Thing to do</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>ThingSelection</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TimeAllotted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TimeAllotted", new List<SelectListItem>
                //"TimeAlloted" has to be one word just like the model
                {
                    new SelectListItem{ Text="5 min", Value = "5"},
                    new SelectListItem{ Text="15 min", Value = "15"},
                    new SelectListItem{ Text="30 min", Value = "30"},
                    new SelectListItem{ Text="45 min", Value = "45"},
                    new SelectListItem{ Text="1 hour", Value = "60"},
                    new SelectListItem{ Text="1 and a 1/2 hours", Value = "90"},
                    new SelectListItem{ Text="2 hours", Value = "120"},
                    new SelectListItem{ Text="3 hours", Value = "180"},
                })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CatagoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CatagoryId, new SelectList(ViewBag.Catagories, "CatagoryId", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CatagoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Find" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<table class="table">
    <tr>
        <th>
            Catagory Name
        </th>
        <th>
            Heading
        </th>
        <th>
            Time (in Min)
        </th>
        <th>
            Date Added
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.ThingsSelected)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeAlloted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            <td>
                @Html.ActionLink("Did you do it?", "Edit", new { id = item.ThingId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ThingId }) |
                @Html.ActionLink("Resources", "IndexByThing", "Resource", new { id = item.ThingId }, null)
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("< I don't want to do a Thing", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoWhat.WebMVC/Views/Thing/SelectedThingIndex.cshtml
@model IEnumerable<DoWhat.Models.ThingModels.ThingListItem>

@{
    ViewBag.Title = "SelectedThingIndex";
}

<h2>Selected Thing Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Catagory.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Heading)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeAlloted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeAlloted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ThingId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ThingId }) |
                @Html.ActionLink("Resources", "IndexByThing", "Resource", new { id = item.ThingId }, null)
            </td>
        </tr>
    }

</table>